const router = require('express').Router();
const controller = require('../controllers/userController');
const { protect, restrictTo } = require('../middlewares/auth');
router.use(protect, restrictTo('coordinator'));
router.get('/', controller.list);
router.post('/', controller.create);
router.get('/:id', controller.get);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
router.patch('/:id/roles', controller.updateRoles);
module.exports = router;
