import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useAxiosFetch } from '../hooks/useAxiosFetch';
import { Loading, ErrorState } from '../components/common/States';
import { Page } from './Page';
interface Stats { defensesPerDay: Record<string, number>; averageScorePerCriterion: Record<string, number>; passRate: number; passingMark: number; panelistLoad: { user: { _id: string; name: string }; defenseCount: number }[]; }
export function Dashboard() {
  const { user, activeView } = useAuth(); const coordinator = Boolean(user?.roles?.includes('coordinator') && activeView === 'coordinator'); const { data, loading, error } = useAxiosFetch<Stats>('/stats/overview', coordinator);
  if (!coordinator) return <Page eyebrow="YOUR WORKSPACE" title={`Welcome, ${user?.name.split(' ')[0]}`} description="Choose the view for your role to continue."><div className="tile-grid"><Link className="action-tile" to={user?.type === 'student' ? '/my-defense' : '/assignments'}><span className="tile-icon">↗</span><h2>{user?.type === 'student' ? 'My defense' : 'My assignments'}</h2><p>{user?.type === 'student' ? 'View your group schedule, panel, status and result.' : 'Review assigned defenses and submit evaluations.'}</p></Link>{user?.type === 'faculty' && <Link className="action-tile" to="/assignments"><span className="tile-icon">◷</span><h2>Panelist workspace</h2><p>See upcoming assignments and evaluation status.</p></Link>}</div></Page>;
  return <Page eyebrow="COORDINATOR OVERVIEW" title="Good work starts with a clear plan." description="A live picture of defense activity across the capstone cycle." action={<Link className="button button-primary" to="/defenses/new">Schedule a defense</Link>}>
    {loading ? <Loading /> : error ? <ErrorState message={error} /> : data && <><div className="stat-grid"><article className="stat-card"><span>Defenses scheduled</span><strong>{Object.values(data.defensesPerDay).reduce((sum, n) => sum + n, 0)}</strong><small>Across {Object.keys(data.defensesPerDay).length} defense days</small></article><article className="stat-card"><span>Pass rate</span><strong>{Math.round(data.passRate * 100)}%</strong><small>Passing mark {data.passingMark}</small></article><article className="stat-card"><span>Criteria evaluated</span><strong>{Object.keys(data.averageScorePerCriterion).length}</strong><small>Average scores recorded</small></article></div><div className="content-grid"><section className="panel-card"><div className="section-title"><div><span className="eyebrow">ACTIVITY</span><h2>Defenses per day</h2></div><Link to="/defenses">View calendar →</Link></div>{Object.keys(data.defensesPerDay).length ? Object.entries(data.defensesPerDay).map(([date, count]) => <div className="metric-row" key={date}><span>{date}</span><strong>{count} defense{count === 1 ? '' : 's'}</strong></div>) : <p className="muted">No defenses scheduled yet.</p>}</section><section className="panel-card"><div className="section-title"><div><span className="eyebrow">PANEL WORKLOAD</span><h2>Faculty distribution</h2></div></div>{data.panelistLoad.length ? data.panelistLoad.map((item) => <div className="metric-row" key={item.user._id}><span>{item.user.name}</span><strong>{item.defenseCount}</strong></div>) : <p className="muted">No faculty accounts yet.</p>}</section></div><section className="panel-card criteria-card"><div className="section-title"><div><span className="eyebrow">RESULTS</span><h2>Average score by criterion</h2></div></div>{Object.keys(data.averageScorePerCriterion).length ? Object.entries(data.averageScorePerCriterion).map(([name, score]) => <div className="metric-row" key={name}><span>{name}</span><strong>{score.toFixed(1)}</strong></div>) : <p className="muted">Scores appear here after evaluations are submitted.</p>}</section></>}
  </Page>;
}
