import { useAxiosFetch } from '../hooks/useAxiosFetch';
import { Loading, ErrorState } from '../components/common/States';
import { Page } from './Page';
import type { Defense, Group } from '../types';
interface StudentDefense { group: Group; defense: Defense | null; averageScore: number | null; }
export function MyDefense() {
  const { data, loading, error } = useAxiosFetch<StudentDefense | null>('/defenses/mine');
  return <Page eyebrow="STUDENT VIEW" title="My defense" description="Your group’s schedule, panel, status, and results.">{loading ? <Loading /> : error ? <ErrorState message={error} /> : !data ? <div className="state-card empty-state">You are not currently assigned to a capstone group.</div> : <div className="student-view"><section className="panel-card"><span className="eyebrow">YOUR PROJECT</span><h2>{data.group.title}</h2><p>{data.group.projectArea}</p><div className="metric-row"><span>Project adviser</span><strong>{data.group.adviser.name}</strong></div><div className="metric-row"><span>Group status</span><strong className="text-capitalize">{data.group.status}</strong></div><div className="student-members">{data.group.members.map((member) => <span key={member._id}>{member.name}</span>)}</div></section>{data.defense ? <section className="panel-card"><span className="eyebrow">DEFENSE DETAILS</span><h2>{new Date(data.defense.startTime).toLocaleDateString(undefined, { dateStyle: 'full' })}</h2><p>{new Date(data.defense.startTime).toLocaleTimeString()} – {new Date(data.defense.endTime).toLocaleTimeString()} · {data.defense.room.name}</p><div className="metric-row"><span>Status</span><span className="status-pill">{data.defense.status}</span></div><h3>Panel</h3><div className="metric-row"><span>{data.defense.chair.name}</span><strong>Chair</strong></div>{data.defense.members.map((person) => <div className="metric-row" key={person._id}><span>{person.name}</span><strong>Member</strong></div>)}<div className="metric-row"><span>Average score</span><strong>{data.averageScore === null ? 'Not available' : data.averageScore.toFixed(1)}</strong></div></section> : <div className="state-card empty-state">Your group’s defense has not been scheduled yet.</div>}</div>}</Page>;
}
