import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { api } from '../services/api';
import { roomSchema, type RoomInput } from '../schemas/forms';
import { useAxiosFetch } from '../hooks/useAxiosFetch';
import { Loading, ErrorState, EmptyState } from '../components/common/States';
import { Page } from './Page';
import type { Room } from '../types';
export function Rooms() {
  const { data, loading, error, reload } = useAxiosFetch<Room[]>('/rooms'); const [editing, setEditing] = useState<Room | null>(null); const [serverError, setServerError] = useState('');
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<RoomInput>({ resolver: zodResolver(roomSchema) });
  const beginEdit = (room: Room) => { setEditing(room); reset({ name: room.name, capacity: room.capacity, equipment: room.equipment.join(', ') }); };
  const submit = async (values: RoomInput) => { setServerError(''); const payload = { ...values, equipment: values.equipment?.split(',').map((part) => part.trim()).filter(Boolean) || [] }; try { if (editing) await api.put(`/rooms/${editing._id}`, payload); else await api.post('/rooms', payload); setEditing(null); reset({ name: '', capacity: 1, equipment: '' }); await reload(); window.alert(editing ? 'Room updated.' : 'Room created.'); } catch (cause: unknown) { setServerError((cause as { response?: { data?: { message?: string } } }).response?.data?.message || 'Could not save room'); } };
  const remove = async (room: Room) => { if (!window.confirm(`Delete ${room.name}?`)) return; try { await api.delete(`/rooms/${room._id}`); await reload(); window.alert('Room deleted.'); } catch (cause: unknown) { window.alert((cause as { response?: { data?: { message?: string } } }).response?.data?.message || 'Delete failed'); } };
  return <Page eyebrow="FACILITIES" title="Defense rooms" description="Manage rooms and equipment for scheduled defenses."><form className="form-card inline-form" onSubmit={handleSubmit(submit)}><div className="section-title"><div><span className="eyebrow">{editing ? 'UPDATE ROOM' : 'NEW ROOM'}</span><h2>{editing ? editing.name : 'Add a room'}</h2></div>{editing && <button type="button" className="link-button" onClick={() => { setEditing(null); reset(); }}>Cancel edit</button>}</div><div className="form-three"><label>Room name<input {...register('name')} placeholder="Room 204" />{errors.name && <small className="field-error">{errors.name.message}</small>}</label><label>Capacity<input type="number" min="1" {...register('capacity')} />{errors.capacity && <small className="field-error">{errors.capacity.message}</small>}</label><label>Equipment <span className="muted">comma separated</span><input {...register('equipment')} placeholder="Projector, whiteboard" /></label></div>{serverError && <ErrorState message={serverError} />}<button className="button button-primary" disabled={isSubmitting}>{editing ? 'Save room' : 'Add room'}</button></form>{loading ? <Loading /> : error ? <ErrorState message={error} /> : !data?.length ? <EmptyState>No rooms have been added yet.</EmptyState> : <div className="card-grid room-grid">{data.map((room) => <article className="group-card room-card" key={room._id}><div className="room-symbol">▦</div><h2>{room.name}</h2><p>Capacity {room.capacity}</p><div className="tag-row">{room.equipment.map((item) => <span key={item}>{item}</span>)}</div><div className="card-actions"><button className="link-button" onClick={() => beginEdit(room)}>Edit</button><button className="link-button danger-link" onClick={() => void remove(room)}>Delete</button></div></article>)}</div>}</Page>;
}
